- include_tasks:
    file: platform.yml
    apply:
      tags:
        - app
        - app.platform
  tags:
    - app
    - app.platform

- include_tasks:
    file: storage.yml
    apply:
      tags:
        - app
        - app.storage
  tags:
    - app
    - app.storage

- include_tasks:
    file: apache.yml
    apply:
      tags:
        - app
        - app.apache
  tags:
    - app
    - app.apache

- include_tasks:
    file: tomcat.yml
    apply:
      tags:
        - app
        - app.tomcat
  tags:
    - app
    - app.tomcat
