- include_tasks:
    file: platform.yml
    apply:
      tags:
        - app
        - app.platform
  tags:
    - app
    - app.platform

- include_tasks:
    file: storage.yml
    apply:
      tags:
        - app
        - app.storage
  tags:
    - app
    - app.storage
