- include_tasks:
    file: platform.yml
    apply:
      tags:
        - app
        - app.platform
  tags:
    - app
    - app.platform

- include_tasks:
    file: storage.yml
    apply:
      tags:
        - app
        - app.storage
  tags:
    - app
    - app.storage

- when: >-
    "app.migrate" in ansible_run_tags
    or
    "app.migrate.legacy-backup" in ansible_run_tags
    or
    "app.migrate.restore" in ansible_run_tags
  include_tasks:
    file: migrate.yml
    apply:
      tags:
        - app
        - app.migrate
  tags:
    - app
    - app.migrate
    - app.migrate.legacy-backup
    - app.migrate.restore
