- name: "Build tools"
  include_tasks:
    file: tools.yml
    apply:
      tags:
        - build
        - build.tools
  tags:
    - build
    - build.tools

- name: "Build Polywiki"
  include_tasks:
    file: polywiki.yml
    apply:
      tags:
        - build
        - build.polywiki
  tags:
    - build
    - build.polywiki

- name: "Install Polywiki"
  include_tasks:
    file: install.yml
    apply:
      tags:
        - build
        - install
        - build.install
  tags:
    - build
    - install
    - build.install
