nginx_tomcat_tls_prefix: /etc/nginx/tls/tomcat
nginx_tomcat_dn_o: EPFL
tomcat_version: 10.1.49
tomcat_archive_url: https://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version.split('.')[0] }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
tomcat_install_dir: /usr/local/share/tomcat
tomcat_download_dir: /tmp
tomcat_logs_dir: /var/log/tomcat
tomcat_user: tomcat
tomcat_group: tomcat

# RHEL 10 layout, discovered with `ls -l /usr/share/tomcat`
tomcat_symlinks:
  - stem: conf
    target: /etc/tomcat
  - stem: logs
    target: "{{ tomcat_logs_dir }}"
  - stem: temp
    target: /var/cache/tomcat/temp
  - stem: webapps
    target: /var/lib/tomcat/webapps
  - stem: webapps-javaee
    target: /var/lib/tomcat/webapps-javaee
  - stem: work
    target: /var/cache/tomcat/work
