- include_tasks:
    file: security.yml
    apply:
      tags:
        - vm
        - vm.security
  tags:
    - vm
    - vm.security

- include_tasks:
    file: access.yml
    apply:
      tags:
        - vm
        - vm.access
  tags:
    - vm
    - vm.access
