- include_tasks:
    file: security.yml
    apply:
      tags:
        - vm
        - vm.security
  tags:
    - vm
    - vm.security

- include_tasks:
    file: access.yml
    apply:
      tags:
        - vm
        - vm.access
  tags:
    - vm
    - vm.access

- include_tasks:
    file: centos.yml
    apply:
      tags:
        - vm
        - vm.centos
  tags:
    - vm
    - vm.centos

- include_tasks:
    file: ipv6.yml
    apply:
      tags:
        - vm
        - vm.ipv6
  tags:
    - vm
    - vm.ipv6

- include_tasks:
    file: s3.yml
    apply:
      tags:
        - vm
        - vm.s3
  tags:
    - vm
    - vm.s3

- include_tasks:
    file: mariadb.yml
    apply:
      tags:
        - vm
        - vm.mariadb
  tags:
    - vm
    - vm.mariadb

- include_tasks:
    file: nfs.yml
    apply:
      tags:
        - vm
        - vm.nfs
  tags:
    - vm
    - vm.nfs
